CREATE TABLE RAZVOJ.VRSTA_PUBLIKACIJE
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(20) NOT NULL,
PRIMARY KEY (id)
);

INSERT INTO RAZVOJ.VRSTA_PUBLIKACIJE (naziv) VALUES ('ELEKTRONICKA');
INSERT INTO RAZVOJ.VRSTA_PUBLIKACIJE (naziv) VALUES ('PAPIRNATA');

CREATE TABLE RAZVOJ.JEZIK
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(20) NOT NULL,
PRIMARY KEY (id)
);

INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('HRVATSKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('ENGLESKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('NJEMACKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('FRANCUSKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('TALIJANSKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('RUSKI');
INSERT INTO RAZVOJ.JEZIK (naziv) VALUES ('KINESKI');

CREATE TABLE RAZVOJ.IZDAVAC
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(50) NOT NULL,
drzava VARCHAR(20) NOT NULL,
PRIMARY KEY (id)
);

INSERT INTO RAZVOJ.IZDAVAC (naziv, drzava) VALUES ('Školska knjiga', 'Hrvatska');
INSERT INTO RAZVOJ.IZDAVAC (naziv, drzava) VALUES ('Packt Publishing', 'SAD');

CREATE TABLE RAZVOJ.KNJIGA
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(50) NOT NULL,
godinaIzdanja INT NOT NULL,
vrstaPublikacije INT NOT NULL,
brojStranica INT NOT NULL,
jezik INT NOT NULL,
izdavac INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (vrstaPublikacije) REFERENCES RAZVOJ.VRSTA_PUBLIKACIJE(id),
FOREIGN KEY (jezik) REFERENCES RAZVOJ.JEZIK(id),
FOREIGN KEY (izdavac) REFERENCES RAZVOJ.IZDAVAC(id)
);

INSERT INTO RAZVOJ.KNJIGA (naziv, godinaIzdanja, vrstaPublikacije, brojStranica, jezik, izdavac) VALUES ('Programiranje u Javi', 2014, 2, 400, 1, 1);
INSERT INTO RAZVOJ.KNJIGA (naziv, godinaIzdanja, vrstaPublikacije, brojStranica, jezik, izdavac) VALUES ('Harry Potter', 2001, 2, 600, 7, 1);
INSERT INTO RAZVOJ.KNJIGA (naziv, godinaIzdanja, vrstaPublikacije, brojStranica, jezik, izdavac) VALUES ('Vlak u snijegu', 1999, 1, 200, 2, 1);

CREATE TABLE RAZVOJ.CASOPIS
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(20) NOT NULL,
godinaIzdanja INT NOT NULL,
vrstaPublikacije INT NOT NULL,
brojStranica INT NOT NULL,
mjesecIzdanja INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (vrstaPublikacije) REFERENCES RAZVOJ.VRSTA_PUBLIKACIJE(id)
);

INSERT INTO RAZVOJ.CASOPIS (naziv, godinaIzdanja, vrstaPublikacije, brojStranica, mjesecIzdanja) VALUES ('Bug', 2014, 2,200,5);
INSERT INTO RAZVOJ.CASOPIS (naziv, godinaIzdanja, vrstaPublikacije, brojStranica, mjesecIzdanja) VALUES ('AutoMoto', 2009, 1,100,4);

CREATE TABLE RAZVOJ.CLAN
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
oib CHAR(11) NOT NULL,
ime VARCHAR(50) NOT NULL,
prezime VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
);

INSERT INTO RAZVOJ.CLAN (oib, ime, prezime) VALUES ('323123', 'Matej','Bilic');
INSERT INTO RAZVOJ.CLAN (oib, ime, prezime) VALUES ('121232', 'Vanja','Bilic');

CREATE TABLE RAZVOJ.POSUDBA_KNJIGA
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
clan INT NOT NULL,
knjiga INT NOT NULL,
datumPosudbe DATE NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (clan) REFERENCES RAZVOJ.CLAN(id),
FOREIGN KEY (knjiga) REFERENCES RAZVOJ.KNJIGA(id)
);

CREATE TABLE RAZVOJ.POSUDBA_CASOPIS
(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
casopis INT NOT NULL,
clan INT NOT NULL,
datumPosudbe DATE NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (clan) REFERENCES RAZVOJ.CLAN(id),
FOREIGN KEY (casopis) REFERENCES RAZVOJ.CASOPIS(id)
);

SELECT * FROM RAZVOJ.CASOPIS;
SELECT * FROM RAZVOJ.KNJIGA; 
SELECT * FROM RAZVOJ.IZDAVAC;
SELECT * FROM RAZVOJ.CLAN;
SELECT * FROM RAZVOJ.JEZIK; 
SELECT * FROM RAZVOJ.VRSTA_PUBLIKACIJE;
SELECT * FROM RAZVOJ.POSUDBA_CASOPIS; 
SELECT * FROM RAZVOJ.POSUDBA_KNJIGA; 


DELETE FROM RAZVOJ.VRSTA_PUBLIKACIJE WHERE ID=3;
DROP TABLE RAZVOJ.IZAVAC;

SELECT id FROM RAZVOJ.KNJIGA WHERE id is max;
SELECT MAX(id) FROM RAZVOJ.KNJIGA
SELECT MAX(id) FROM RAZVOJ.IZDAVAC

UPDATE RAZVOJ.IZDACAC SET naziv=?, drzaca=? WHERE id=?; 
UPDATE RAZVOJ.KNJIGA SET naziv=?, godinaizdanja=?, vrstapublikacije=?, brojstranica=?, jezik=?, izdacac=? WHERE id=?;


